### ISSUE TITLE
Execution failed for task ':react-native-firebase:compileDebugJavaWithJavac'

### ISSUE THREAD

**Issue by HunterSHeston** [invertase/react-native-firebase-starter#25]
Looks like my project can't find the HeadlessJsTaskService class from com.facebook.react. Followed the instructions from [here](https://rnfirebase.io/docs/v4.0.x/installation/basic-kit).

Output I'm getting when running `npm run android` :

```
> Task :react-native-firebase:compileDebugJavaWithJavac FAILED
/home/hunter/workspace/react/react-native-firebase-starter/node_modules/react-native-firebase/android/src/main/java/io/upandrunning/firebase/messaging/RNFirebaseBackgroundMessagingService.java:6: error: cannot find symbol
import com.facebook.react.HeadlessJsTaskService;
                         ^
  symbol:   class HeadlessJsTaskService
  location: package com.facebook.react
/home/hunter/workspace/react/react-native-firebase-starter/node_modules/react-native-firebase/android/src/main/java/io/upandrunning/firebase/messaging/RNFirebaseBackgroundMessagingService.java:9: error: package com.facebook.react.jstasks does not exist
import com.facebook.react.jstasks.HeadlessJsTaskConfig;
                                 ^
/home/hunter/workspace/react/react-native-firebase-starter/node_modules/react-native-firebase/android/src/main/java/io/upandrunning/firebase/messaging/RNFirebaseBackgroundMessagingService.java:14: error: cannot find symbol
public class RNFirebaseBackgroundMessagingService extends HeadlessJsTaskService {
                                                          ^
```

Please let me know if there is any additional information I can provide.

**Comment by HunterSHeston** [comment]
OS: Ubuntu 17.10  if it helps.

**Comment by iooi** [comment]
Same issue on Mac - the starter kit can't build for Android. Please fix!

**Comment by egunsoma** [comment]
Same here, on Mac.

**Comment by iooi** [comment]
I think it has been fixed in latest check-in, by rolling back firestore to 15? Anyway, thank you!

**Comment by matheuschagas** [comment]
same issue here

**Comment by DatMoser** [comment]
Still have this problem, but with another Error:


```
> Task :react-native-firebase:compileDebugJavaWithJavac FAILED
/Users/myname/Documents/name/Programmierungen/Project/node_modules/react-native-firebase/android/src/main/java/io/invertase/firebase/perf/RNFirebasePerformance.java:50: error: cannot access zzf
    promise.resolve(getOrCreateTrace(identifier).getAttribute(attribute));
                                                ^
  class file for com.google.android.gms.internal.firebase-perf.zzf not found
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error
```

Works fine on IOS and I`ve just followed the steps to implement Firebase into an existing project,
Using:
"react": "16.5.0",
    "react-native": "^0.57.1",
    "react-native-firebase": "^5.0.0"

Any help, please `:D

**Comment by choogendoorn** [comment]
Same here, been trying to get this to work for days now..

**Comment by TomOConnor95** [comment]
I had this problem and it was due to using the wrong version of the java SDK. 
run `javaC -version` to see your version and check its what you were expecting

I was wanting to use v 1.8.0_191, but accidentally had the 10.0.0.1 version installed as well, and it was defaulting to use the higher version.

See this link for seeing and uninstalling versions, then install the correct one and rebuild your application.
http://exponential.io/blog/2015/01/27/uninstall-oracle-java-on-mac/
