### ISSUE TITLE
Could not invoke RNFirebaseFirestore.collectionOnSnapshot

### ISSUE THREAD

**Issue by egunsoma** [invertase/react-native-firebase-starter#30]
@chrisbianca Can this error be related to the recent Android fix in 6b665d70301631de64dcb7e5657b3ad9475e850d? iOS works fine.

Platform: Android
Version:`"react-native-firebase": "^4.0.7"`

**Whole error message:**
```
Could not invoke RNFirebaseFirestore.collectionOnSnapshot

null

Failed resolution of: Lcom/google/firebase/firestore/QueryListenOptions;

Didn't find class "com.google.firebase.firestore.QueryListenOptions" on path: DexPathList[[zip file "/data/app/com.company.realtimechat-1/base.apk"],nativeLibraryDirectories=[/data/app/com.company.realtimechat-1/lib/x86, /system/fake-libs, /data/app/com.company.realtimechat-1/base.apk!/lib/x86, /system/lib, /vendor/lib]]
invoke
    JavaMethodWrapper.java:383
invoke
    JavaModuleWrapper.java:160
run
    NativeRunnable.java
handleCallback
    Handler.java:751
dispatchMessage
    Handler.java:95
dispatchMessage
    MessageQueueThreadHandler.java:29
loop
    Looper.java:154
run
    MessageQueueThreadImpl.java:192
run
    Thread.java:761
```

**Comment by egunsoma** [comment]
Runtime, after build succeeded.

**Comment by chrisbianca** [comment]
Looks like there were some breaking changes in firestore v16, I've just pushed up a fix to this repo which reverts the firestore lib to v16: https://github.com/invertase/react-native-firebase-starter/commit/00309327bbb7bf457101f9d940e03a48cf1c3d73

**Comment by egunsoma** [comment]
@chrisbianca Thank you, it's working now! ✅

**Comment by kkusanagi** [comment]
I still get this error in runtime for v4.2.0.

Any stable version advise?
