### ISSUE TITLE
Unable to load script from assets 'index.android.bundle'. In release apk

### ISSUE THREAD

**Issue by Jeffrey-Dozva** [invertase/react-native-firebase-starter#73]
```
Fatal Exception: java.lang.RuntimeException
Unable to load script from assets 'index.android.bundle'. Make sure your bundle is packaged correctly or you're running a packager server.
com.facebook.react.bridge.CatalystInstanceImpl.jniLoadScriptFromAssets (CatalystInstanceImpl.java)
com.facebook.react.bridge.CatalystInstanceImpl.loadScriptFromAssets (CatalystInstanceImpl.java:216)
com.facebook.react.bridge.JSBundleLoader$1.loadScript (JSBundleLoader.java:32)
com.facebook.react.bridge.CatalystInstanceImpl.runJSBundle (CatalystInstanceImpl.java:243)
com.facebook.react.ReactInstanceManager.createReactContext (ReactInstanceManager.java:1114)
com.facebook.react.ReactInstanceManager.access$900 (ReactInstanceManager.java:116)
com.facebook.react.ReactInstanceManager$5.run (ReactInstanceManager.java:913)
java.lang.Thread.run (Thread.java:818)
```

**Comment by haizen007** [comment]
same issue here

**Comment by egunsoma** [comment]
same here.
https://facebook.github.io/react-native/docs/signed-apk-android#generating-the-release-apk
the yellow section mentions not to include org.gradle.configureondemand=true, while its present in the gradle properties by default. Any suggestions? I've tried removing it, problem still occurs.

**Comment by egunsoma** [comment]
Solution here @haizen007  @Jeffrey-Dozva!
https://github.com/facebook/react-native/issues/18357#issuecomment-425728542
In this comment @bhardman1986 advices to downgrade gradle and add the android.enableAapt2=false gradle property. Im not sure if it's a good idea at all, but it sure solves the problem.

@Salakar what do you think about this solution? Can we introduce this to the starter pack?

**Comment by egunsoma** [comment]
I've tried upgrading react native to 0.57.4, and I can confirm it works :) thanks @Jeffrey-Dozva

**Comment by Salakar** [comment]
A PR to upgrade to 57.4 would be great if someone can send one over =] the starter is now on RNFB v5.1.0 also - I released it earlier and updated the starter

**Comment by FirefighterBlu3** [comment]
react-native 57.8, didn't fix. following [these instructions](https://stackoverflow.com/questions/44446523/unable-to-load-script-from-assets-index-android-bundle-on-windows) fixed it:

1. (in project directory) `mkdir android/app/src/main/assets`
1. `react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res`
1. `react-native run-android` (or `npm run android`)
